#!/bin/bash

NAME="notification-configurator"
DOMAIN="exposedcat"

SLUG="$NAME@$DOMAIN"
EXTENSIONS="/home/$USER/.local/share/gnome-shell/extensions"

build() {
  npx tsc
  cp -r metadata.json schemas dist
  glib-compile-schemas ./dist/schemas
}

inject() {
	build
  mkdir -p "$EXTENSIONS"
  rm -rf "${EXTENSIONS:?}/$SLUG"
  mv dist "$EXTENSIONS/$SLUG"
}

case $1 in
clean)
  rm -rf dist node_modules $NAME.zip
  ;;
build)
  build
  ;;
pack)
  rm -f $NAME.zip
  pushd dist || exit
  zip "../$NAME.zip" -9r ./*.js ./*.css ./**/*.js ./**/*.css metadata.json
  popd || exit
  ;;
inject)
	inject
  ;;
uninstall)
  rm -rf "${EXTENSIONS:?}/$SLUG"
  ;;
dev)
  build
  inject
  dbus-run-session -- gnome-shell --nested --wayland
  ;;
*)
  echo "Unknown command '$1'"
  ;;
esac
